package: yform
version: '4.0.0'
author: 'Jan Kristinus, Gregor Harlan'
supportpage: 'https://github.com/yakamara/redaxo_yform/issues'
compile: 0

page:
    title: 'translate:yform'
    pjax: false
    icon: rex-icon rex-icon-module
    subpages:
        setup:
            title: 'translate:setup'
            perm: admin
        docs:
            title: 'translate:docs'
            perm: admin[]
            pjax: false
            itemclass: pull-right
            icon: rex-icon fa-info-circle

stylesheets:
    - yform.css
    - popup.css

requires:
    redaxo: '^5.13.0'
    php:
        version: '>=7, <9'

system_plugins:
    - manager
    - email
conflicts:
    packages:
        quick_navigation: '<5.2.1'
        yform_geo_osm: '<1.2.5'
        redaxo_watson: '<2.1.1'
        yform_spam_protection: '<1.2.0'
        ycom: '<4.0.6'
