package: yform
version: '4.0.0-dev2'
author: 'Jan Kristinus, Gregor Harlan'
supportpage: 'https://github.com/yakamara/redaxo_yform/issues'

page:
    title: 'translate:yform'
    pjax: false
    icon: rex-icon rex-icon-module
    subpages:
        overview:
            title: 'translate:overview'
            perm: admin
        docs:
            title: 'translate:docs'
            perm: admin[]
            pjax: false
            itemclass: pull-right
            icon: rex-icon fa-info-circle

stylesheets:
    - yform.css
    - popup.css

requires:
    packages:
        phpmailer: '^2.0.0'
    redaxo: '^5.8.0'
    php:
        version: '>=7, <9'

system_plugins:
    - manager
    - email
