package: yform
version: '4.2.1'
license: MIT
author: 'Jan Kristinus, Gregor Harlan'
supportpage: 'https://github.com/yakamara/yform/issues'
compile: 0

page:
    title: 'translate:yform'
    pjax: false
    icon: rex-icon rex-icon-module
    subpages:
        setup:
            title: 'translate:setup'
            perm: admin
        docs:
            title: 'translate:docs'
            perm: admin[]
            pjax: false
            itemClass: pull-right
            icon: rex-icon fa-info-circle
        email:
            title: 'translate:yform_email_templates'
            perm: admin[]
            pjax: true
        rest:
            title: 'translate:yform_rest'
            pjax: true
            perm: admin
            subpages:
                token: {title: translate:yform_rest_token}
                access: {title: translate:yform_rest_token_access}

stylesheets:
    - yform.css
    - popup.css

requires:
    redaxo: '^5.17.0'
    php:
        version: '^8.1'

system_plugins:
    - manager
    - email

installer_ignore:
    - .tools
